### ISSUE TITLE
Can you provide a Dockerfile?

### ISSUE THREAD

**Issue by ai-motive** [D641593/MixNet#1]
Thank you for distributing your wonderful research results. :)

Can you provide a dockerfile for the same development environment?

**Comment by D641593** [comment]
Yes, we will update the docker environment.
Please allow us some time for this process.

**Comment by gioivuathoi** [comment]
@D641593 Thank you for sharing your great work. 
The docker image you provide is too big, my downloading process is collapsed every time I try to download. 
So is it possible to upload your dockerfile and docker compose file for testing arbitrary image so that I can adjust and build myself.
Thank you!!
